@api_HostAddress = http://localhost:5223
@deviceId = 101
@autoId = 101
@status = 1

PUT {{api_HostAddress}}/api/device/limit?deviceId={{deviceId}}
Content-Type: application/json

{
	"isAutoSinglePhase": false,
	"l1": { "isVol": false, "minVol": 0, "maxVol": 0, "isA": false, "minA": 0, "maxA": 0 },
	"l2": { "isVol": false, "minVol": 0, "maxVol": 0, "isA": false, "minA": 0, "maxA": 0 },
	"l3": { "isVol": false, "minVol": 0, "maxVol": 0, "isA": false, "minA": 0, "maxA": 0 },
	"ln": { "isVol": false, "minVol": 0, "maxVol": 0, "isA": false, "minA": 0, "maxA": 0 }
}

###

GET {{api_HostAddress}}/api/device/limit?deviceId={{deviceId}}
Accept: application/json

###

GET {{api_HostAddress}}/api/device/measurements?deviceId={{deviceId}}
Accept: application/json

###

GET {{api_HostAddress}}/api/device/motor/status?autoId={{autoId}}
Accept: application/json

###

PUT {{api_HostAddress}}/api/device/auto/status?autoId={{autoId}}&status={{status}}

###

GET {{api_HostAddress}}/api/device/auto/status?autoId={{autoId}}
Accept: application/json
